// import { createClient } from '@supabase/supabase-js';
// const supabaseUrl = 'https://oiwsdkbdtmwlbyvrhlxj.supabase.co';
// const supabaseKey =
//   process.env.SUPABASE_KEY ||
//   'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pd3Nka2JkdG13bGJ5dnJobHhqIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NTQyOTUzMSwiZXhwIjoyMDcxMDA1NTMxfQ.2SoeoXl1F-semD7MJiZV92qHyqVxmQ-j_vg-gC0Mc24';

// const supabase = createClient(supabaseUrl, supabaseKey);

// export default supabase;

// This file is automatically generated. Do not edit it directly.
// import 'react-native-url-polyfill/auto';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { createClient } from '@supabase/supabase-js';
// import type { Database } from './types';

const SUPABASE_URL = 'https://oiwsdkbdtmwlbyvrhlxj.supabase.co';
const SUPABASE_PUBLISHABLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pd3Nka2JkdG13bGJ5dnJobHhqIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NTQyOTUzMSwiZXhwIjoyMDcxMDA1NTMxfQ.2SoeoXl1F-semD7MJiZV92qHyqVxmQ-j_vg-gC0Mc24';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Important for RN: persist auth to device storage
    storage: AsyncStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false,
    // pkce is the default; implicit also works for email+password flows
    flowType: 'pkce',
  },
});
